typedef sequence<string> EchoList;
typedef sequence<float> ValueList;
typedef float Values;

struct TestStruct {
  double a;
  double b;
};

typedef TestStruct StrVal;

interface MyService
{
  string echo(in TestStruct msg);
  EchoList get_echo_history(in EchoList echoList);
  void set_value(in float value);
  float get_value(inout TestStruct value);
  ValueList get_value_history();
  Values get_test_value(in Values test);
  void get_test_value2(inout StrVal test);
};
