# Python stubs generated by omniidl from MyService.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(2,0, __file__)

try:
    _omniORB_StructBase = omniORB.StructBase
except AttributeError:
    class _omniORB_StructBase: pass


#
# Start of module "_GlobalIDL"
#
__name__ = "_GlobalIDL"
_0__GlobalIDL = omniORB.openModule("_GlobalIDL", r"MyService.idl")
_0__GlobalIDL__POA = omniORB.openModule("_GlobalIDL__POA", r"MyService.idl")


# interface MyService
_0__GlobalIDL._d_MyService = (omniORB.tcInternal.tv_objref, "IDL:MyService:1.0", "MyService")
omniORB.typeMapping["IDL:MyService:1.0"] = _0__GlobalIDL._d_MyService
_0__GlobalIDL.MyService = omniORB.newEmptyClass()
class MyService :
    _NP_RepositoryId = _0__GlobalIDL._d_MyService[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0__GlobalIDL.MyService = MyService
_0__GlobalIDL._tc_MyService = omniORB.tcInternal.createTypeCode(_0__GlobalIDL._d_MyService)
omniORB.registerType(MyService._NP_RepositoryId, _0__GlobalIDL._d_MyService, _0__GlobalIDL._tc_MyService)

# MyService operations and attributes
MyService._d_echo01 = ((omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_short), (omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_short, omniORB.tcInternal.tv_short), None)
MyService._d_echo02 = ((omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long), (omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long), None)
MyService._d_echo03 = ((omniORB.tcInternal.tv_longlong, omniORB.tcInternal.tv_longlong), (omniORB.tcInternal.tv_longlong, omniORB.tcInternal.tv_longlong, omniORB.tcInternal.tv_longlong), None)
MyService._d_echo04 = ((omniORB.tcInternal.tv_ulong, omniORB.tcInternal.tv_ulong), (omniORB.tcInternal.tv_ulong, omniORB.tcInternal.tv_ulong, omniORB.tcInternal.tv_ulong), None)
MyService._d_echo05 = ((omniORB.tcInternal.tv_ulonglong, omniORB.tcInternal.tv_ulonglong), (omniORB.tcInternal.tv_ulonglong, omniORB.tcInternal.tv_ulonglong, omniORB.tcInternal.tv_ulonglong), None)
MyService._d_echo06 = ((omniORB.tcInternal.tv_ushort, omniORB.tcInternal.tv_ushort), (omniORB.tcInternal.tv_ushort, omniORB.tcInternal.tv_ushort, omniORB.tcInternal.tv_ushort), None)
MyService._d_echo07 = ((omniORB.tcInternal.tv_float, omniORB.tcInternal.tv_float), (omniORB.tcInternal.tv_float, omniORB.tcInternal.tv_float, omniORB.tcInternal.tv_float), None)
MyService._d_echo08 = ((omniORB.tcInternal.tv_double, omniORB.tcInternal.tv_double), (omniORB.tcInternal.tv_double, omniORB.tcInternal.tv_double, omniORB.tcInternal.tv_double), None)
MyService._d_echo10 = ((omniORB.tcInternal.tv_char, omniORB.tcInternal.tv_char), (omniORB.tcInternal.tv_char, omniORB.tcInternal.tv_char, omniORB.tcInternal.tv_char), None)
MyService._d_echo11 = ((omniORB.tcInternal.tv_wchar, omniORB.tcInternal.tv_wchar), (omniORB.tcInternal.tv_wchar, omniORB.tcInternal.tv_wchar, omniORB.tcInternal.tv_wchar), None)
MyService._d_echo12 = ((omniORB.tcInternal.tv_octet, omniORB.tcInternal.tv_octet), (omniORB.tcInternal.tv_octet, omniORB.tcInternal.tv_octet, omniORB.tcInternal.tv_octet), None)
MyService._d_echo13 = ((omniORB.tcInternal.tv_boolean, omniORB.tcInternal.tv_boolean), (omniORB.tcInternal.tv_boolean, omniORB.tcInternal.tv_boolean, omniORB.tcInternal.tv_boolean), None)
MyService._d_echo14 = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), ((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), None)
MyService._d_echo15 = (((omniORB.tcInternal.tv_wstring,0), (omniORB.tcInternal.tv_wstring,0)), ((omniORB.tcInternal.tv_wstring,0), (omniORB.tcInternal.tv_wstring,0), (omniORB.tcInternal.tv_wstring,0)), None)
MyService._d_echo16 = ((omniORB.tcInternal.tv_any, omniORB.tcInternal.tv_any), (omniORB.tcInternal.tv_any, omniORB.tcInternal.tv_any, omniORB.tcInternal.tv_any), None)

# MyService object reference
class _objref_MyService (CORBA.Object):
    _NP_RepositoryId = MyService._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def echo01(self, *args):
        return _omnipy.invoke(self, "echo01", _0__GlobalIDL.MyService._d_echo01, args)

    def echo02(self, *args):
        return _omnipy.invoke(self, "echo02", _0__GlobalIDL.MyService._d_echo02, args)

    def echo03(self, *args):
        return _omnipy.invoke(self, "echo03", _0__GlobalIDL.MyService._d_echo03, args)

    def echo04(self, *args):
        return _omnipy.invoke(self, "echo04", _0__GlobalIDL.MyService._d_echo04, args)

    def echo05(self, *args):
        return _omnipy.invoke(self, "echo05", _0__GlobalIDL.MyService._d_echo05, args)

    def echo06(self, *args):
        return _omnipy.invoke(self, "echo06", _0__GlobalIDL.MyService._d_echo06, args)

    def echo07(self, *args):
        return _omnipy.invoke(self, "echo07", _0__GlobalIDL.MyService._d_echo07, args)

    def echo08(self, *args):
        return _omnipy.invoke(self, "echo08", _0__GlobalIDL.MyService._d_echo08, args)

    def echo10(self, *args):
        return _omnipy.invoke(self, "echo10", _0__GlobalIDL.MyService._d_echo10, args)

    def echo11(self, *args):
        return _omnipy.invoke(self, "echo11", _0__GlobalIDL.MyService._d_echo11, args)

    def echo12(self, *args):
        return _omnipy.invoke(self, "echo12", _0__GlobalIDL.MyService._d_echo12, args)

    def echo13(self, *args):
        return _omnipy.invoke(self, "echo13", _0__GlobalIDL.MyService._d_echo13, args)

    def echo14(self, *args):
        return _omnipy.invoke(self, "echo14", _0__GlobalIDL.MyService._d_echo14, args)

    def echo15(self, *args):
        return _omnipy.invoke(self, "echo15", _0__GlobalIDL.MyService._d_echo15, args)

    def echo16(self, *args):
        return _omnipy.invoke(self, "echo16", _0__GlobalIDL.MyService._d_echo16, args)

    __methods__ = ["echo01", "echo02", "echo03", "echo04", "echo05", "echo06", "echo07", "echo08", "echo10", "echo11", "echo12", "echo13", "echo14", "echo15", "echo16"] + CORBA.Object.__methods__

omniORB.registerObjref(MyService._NP_RepositoryId, _objref_MyService)
_0__GlobalIDL._objref_MyService = _objref_MyService
del MyService, _objref_MyService

# MyService skeleton
__name__ = "_GlobalIDL__POA"
class MyService (PortableServer.Servant):
    _NP_RepositoryId = _0__GlobalIDL.MyService._NP_RepositoryId


    _omni_op_d = {"echo01": _0__GlobalIDL.MyService._d_echo01, "echo02": _0__GlobalIDL.MyService._d_echo02, "echo03": _0__GlobalIDL.MyService._d_echo03, "echo04": _0__GlobalIDL.MyService._d_echo04, "echo05": _0__GlobalIDL.MyService._d_echo05, "echo06": _0__GlobalIDL.MyService._d_echo06, "echo07": _0__GlobalIDL.MyService._d_echo07, "echo08": _0__GlobalIDL.MyService._d_echo08, "echo10": _0__GlobalIDL.MyService._d_echo10, "echo11": _0__GlobalIDL.MyService._d_echo11, "echo12": _0__GlobalIDL.MyService._d_echo12, "echo13": _0__GlobalIDL.MyService._d_echo13, "echo14": _0__GlobalIDL.MyService._d_echo14, "echo15": _0__GlobalIDL.MyService._d_echo15, "echo16": _0__GlobalIDL.MyService._d_echo16}

MyService._omni_skeleton = MyService
_0__GlobalIDL__POA.MyService = MyService
del MyService
__name__ = "_GlobalIDL"

#
# End of module "_GlobalIDL"
#
__name__ = "MyService_idl"

_exported_modules = ( "_GlobalIDL", )

# The end.
