#!/bin/sh
find ./ -name '*.class' -exec rm -f {} \;
find ./ -name '*.java' -exec grep -nH 'IDL-to-Java' {} \; -exec rm -f {} \;
find ./ -name '*.html' -exec grep -nH 'Generated by javadoc' {} \; -exec rm -f {} \;
find ./ -name '*aist*.jar' -exec rm -f {} \;
find ./ -name '*.msi' -exec rm -f {} \;

