typedef sequence<string> EchoList;
typedef sequence<float> ValueList;
typedef float Values;

interface MyService
{
  string echo(in string msg);
  EchoList get_echo_history(in EchoList echoList);
  void set_value(in float value);
  float get_value();
  ValueList get_value_history();
  Values get_test_value(in Values test);
};
