//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.26 at 02:15:47 ŒßŒã GMT 
//


package org.openrtp.namespaces.rts;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * <p>Java class for condition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="condition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="WaitTime" type="{http://www.w3.org/2001/XMLSchema}duration"/>
 *         &lt;element name="Preceding" type="{http://www.openrtp.org/namespaces/rts}preceding_component"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "condition", propOrder = {
    "waitTime",
    "preceding"
})
public class Condition {

    @XmlElement(name = "WaitTime")
    protected Duration waitTime;
    @XmlElement(name = "Preceding")
    protected PrecedingComponent preceding;

    /**
     * Gets the value of the waitTime property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getWaitTime() {
        return waitTime;
    }

    /**
     * Sets the value of the waitTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setWaitTime(Duration value) {
        this.waitTime = value;
    }

    /**
     * Gets the value of the preceding property.
     * 
     * @return
     *     possible object is
     *     {@link PrecedingComponent }
     *     
     */
    public PrecedingComponent getPreceding() {
        return preceding;
    }

    /**
     * Sets the value of the preceding property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrecedingComponent }
     *     
     */
    public void setPreceding(PrecedingComponent value) {
        this.preceding = value;
    }

}
