//
// Generated by JTB 1.3.2
//

package jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeOptional -> [ "readonly" ]
 * nodeToken -> "attribute"
 * param_type_spec -> param_type_spec()
 * simple_declarator -> simple_declarator()
 * nodeListOptional -> ( "," simple_declarator() )*
 * </PRE>
 */
public class attr_dcl implements Node {
   private Node parent;
   public NodeOptional nodeOptional;
   public NodeToken nodeToken;
   public param_type_spec param_type_spec;
   public simple_declarator simple_declarator;
   public NodeListOptional nodeListOptional;

   public attr_dcl(NodeOptional n0, NodeToken n1, param_type_spec n2, simple_declarator n3, NodeListOptional n4) {
      nodeOptional = n0;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
      nodeToken = n1;
      if ( nodeToken != null ) nodeToken.setParent(this);
      param_type_spec = n2;
      if ( param_type_spec != null ) param_type_spec.setParent(this);
      simple_declarator = n3;
      if ( simple_declarator != null ) simple_declarator.setParent(this);
      nodeListOptional = n4;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
   }

   public attr_dcl(NodeOptional n0, param_type_spec n1, simple_declarator n2, NodeListOptional n3) {
      nodeOptional = n0;
      if ( nodeOptional != null ) nodeOptional.setParent(this);
      nodeToken = new NodeToken("attribute");
      if ( nodeToken != null ) nodeToken.setParent(this);
      param_type_spec = n1;
      if ( param_type_spec != null ) param_type_spec.setParent(this);
      simple_declarator = n2;
      if ( simple_declarator != null ) simple_declarator.setParent(this);
      nodeListOptional = n3;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
   }

   public void accept(jp.go.aist.rtm.rtcbuilder.corba.idl.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(jp.go.aist.rtm.rtcbuilder.corba.idl.parser.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(jp.go.aist.rtm.rtcbuilder.corba.idl.parser.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(jp.go.aist.rtm.rtcbuilder.corba.idl.parser.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

