//
// Generated by JTB 1.3.2
//

package jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree;

/**
 * Grammar production:
 * <PRE>
 * nodeToken -> ":"
 * scoped_name -> scoped_name()
 * nodeListOptional -> ( "," scoped_name() )*
 * </PRE>
 */
public class inheritance_spec implements Node {
   private Node parent;
   public NodeToken nodeToken;
   public scoped_name scoped_name;
   public NodeListOptional nodeListOptional;

   public inheritance_spec(NodeToken n0, scoped_name n1, NodeListOptional n2) {
      nodeToken = n0;
      if ( nodeToken != null ) nodeToken.setParent(this);
      scoped_name = n1;
      if ( scoped_name != null ) scoped_name.setParent(this);
      nodeListOptional = n2;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
   }

   public inheritance_spec(scoped_name n0, NodeListOptional n1) {
      nodeToken = new NodeToken(":");
      if ( nodeToken != null ) nodeToken.setParent(this);
      scoped_name = n0;
      if ( scoped_name != null ) scoped_name.setParent(this);
      nodeListOptional = n1;
      if ( nodeListOptional != null ) nodeListOptional.setParent(this);
   }

   public void accept(jp.go.aist.rtm.rtcbuilder.corba.idl.parser.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(jp.go.aist.rtm.rtcbuilder.corba.idl.parser.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(jp.go.aist.rtm.rtcbuilder.corba.idl.parser.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(jp.go.aist.rtm.rtcbuilder.corba.idl.parser.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
   public void setParent(Node n) { parent = n; }
   public Node getParent()       { return parent; }
}

