// -*- IDL -*-
/*!
 * @file RTCService.idl
 * @brief RTComponent サービスインターフェース
 * @date $Date: 2007/12/25 05:43:02 $
 * @author Noriaki Ando <n-ando@aist.go.jp>
 *
 * Copyright (C) 2005
 *     Task-intelligence Research Group,
 *     Intelligent Systems Research Institute,
 *     National Institute of
 *         Advanced Industrial Science and Technology (AIST), Japan
 *
 *     All rights reserved.
 *
 * $Id: DAQService.idl,v 1.1 2007/12/25 05:43:02 tsakamoto Exp $
 *
 */

/*
 * $Log: DAQService.idl,v $
 * Revision 1.1  2007/12/25 05:43:02  tsakamoto
 * *** empty log message ***
 *
 * Revision 1.1  2007/03/14 12:14:35  tsakamoto
 * 属性生成版
 *
 * Revision 1.1  2005/09/07 05:06:13  n-ando
 * RTComponent's service management feature was added.
 *
 */

#ifndef __RTCService_idl__
#define __RTCService_idl__

interface DAQService
{
  long setCommand(in long com, in double par);
  short getCommand();
  unsigned long checkDone();
  void setDone();
};

