<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="component"
    nsURI="http:///jp/go/aist/rtm/rtcbuilder/model/component.ecore" nsPrefix="jp.go.aist.rtm.rtcbuilder.model.component">
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eOperations name="addDataInport">
      <eParameters name="inport" eType="#//DataInPort"/>
    </eOperations>
    <eOperations name="addDataOutport">
      <eParameters name="outport" eType="#//DataOutPort"/>
    </eOperations>
    <eOperations name="addServiceport">
      <eParameters name="serviceport" eType="#//ServicePort"/>
    </eOperations>
    <eOperations name="clearDataInports"/>
    <eOperations name="clearDataOutports"/>
    <eOperations name="clearServiceports"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Component_Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DataInPorts" upperBound="-1"
        eType="#//DataInPort" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DataOutPorts" upperBound="-1"
        eType="#//DataOutPort" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ServicePorts" upperBound="-1"
        eType="#//ServicePort" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rightMaxNum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="leftMaxNum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="topMaxNum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bottomMaxNum" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0" unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataInPort" eSuperTypes="#//PortBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="InPort_Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataOutPort" eSuperTypes="#//PortBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OutPort_Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServicePort" eSuperTypes="#//PortBase">
    <eOperations name="addServiceInterface">
      <eParameters name="serviceinterface" eType="#//ServiceInterface"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ServicePort_Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ServiceInterfaces" upperBound="-1"
        eType="#//ServiceInterface" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceInterface">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ServiceInterface_Name"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Direction" eType="#//InterfaceDirection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ParentDirection" eType="#//PortDirection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuildView">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortBase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Direction" eType="#//PortDirection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PortDirection">
    <eLiterals name="Left"/>
    <eLiterals name="Right" value="1"/>
    <eLiterals name="Top" value="2"/>
    <eLiterals name="Bottom" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InterfaceDirection">
    <eLiterals name="Provided"/>
    <eLiterals name="Required" value="1"/>
  </eClassifiers>
</ecore:EPackage>
