//
// Generated by JTB 1.3.2
//

package jp.go.aist.rtm.rtcbuilder.corba.idl.parser.visitor;
import java.util.Enumeration;

import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.Node;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.NodeList;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.NodeListOptional;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.NodeOptional;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.NodeSequence;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.NodeToken;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.add_expr;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.and_expr;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.any_type;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.array_declarator;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.attr_dcl;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.base_type_spec;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.boolean_literal;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.boolean_type;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.case_label;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.casex;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.char_type;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.character_literal;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.complex_declarator;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.const_dcl;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.const_exp;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.const_type;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.constr_type_spec;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.context_expr;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.declarator;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.declarators;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.definition;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.element_spec;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.enum_type;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.enumerator;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.except_dcl;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.export;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.fixed_array_size;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.floating_pt_literal;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.floating_pt_type;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.forward_dcl;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.identifier;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.inheritance_spec;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.integer_literal;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.integer_type;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.interface_body;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.interface_dcl;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.interface_header;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.interfacex;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.literal;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.member;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.member_list;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.module;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.mult_expr;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.octet_type;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.op_attribute;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.op_dcl;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.op_type_spec;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.or_expr;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.param_attribute;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.param_dcl;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.param_type_spec;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.parameter_dcls;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.positive_int_const;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.primary_expr;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.raises_expr;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.scoped_name;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.sequence_type;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.shift_expr;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.signed_int;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.signed_long_double_int;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.signed_long_int;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.signed_long_long_int;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.signed_short_int;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.simple_declarator;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.simple_type_spec;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.specification;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.string_literal;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.string_type;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.struct_type;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.switch_body;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.switch_type_spec;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.template_type_spec;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.type_dcl;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.type_declarator;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.type_spec;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.unary_expr;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.unary_operator;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.union_type;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.unsigned_int;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.unsigned_long_int;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.unsigned_long_long_int;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.unsigned_short_int;
import jp.go.aist.rtm.rtcbuilder.corba.idl.parser.syntaxtree.xor_expr;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJDepthFirst<R,A> implements GJVisitor<R,A> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public R visit(NodeList n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n, A argu) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this,argu);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n, A argu) {
      if ( n.present() )
         return n.node.accept(this,argu);
      else
         return null;
   }

   public R visit(NodeSequence n, A argu) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n, A argu) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * <PRE>
    * nodeList -> ( definition() )+
    * </PRE>
    */
   public R visit(specification n, A argu) {
      R _ret=null;
      n.nodeList.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> type_dcl() ";"
    *       | const_dcl() ";"
    *       | except_dcl() ";"
    *       | interfacex() ";"
    *       | module() ";"
    * </PRE>
    */
   public R visit(definition n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "module"
    * identifier -> identifier()
    * nodeToken1 -> "{"
    * nodeList -> ( definition() )+
    * nodeToken2 -> "}"
    * </PRE>
    */
   public R visit(module n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.identifier.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.nodeList.accept(this, argu);
      n.nodeToken2.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> interface_dcl()
    *       | forward_dcl()
    * </PRE>
    */
   public R visit(interfacex n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * interface_header -> interface_header()
    * nodeToken -> "{"
    * interface_body -> interface_body()
    * nodeToken1 -> "}"
    * </PRE>
    */
   public R visit(interface_dcl n, A argu) {
      R _ret=null;
      n.interface_header.accept(this, argu);
      n.nodeToken.accept(this, argu);
      n.interface_body.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "interface"
    * identifier -> identifier()
    * </PRE>
    */
   public R visit(forward_dcl n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.identifier.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "interface"
    * identifier -> identifier()
    * nodeOptional -> [ inheritance_spec() ]
    * </PRE>
    */
   public R visit(interface_header n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.identifier.accept(this, argu);
      n.nodeOptional.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeListOptional -> ( export() )*
    * </PRE>
    */
   public R visit(interface_body n, A argu) {
      R _ret=null;
      n.nodeListOptional.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> type_dcl() ";"
    *       | const_dcl() ";"
    *       | except_dcl() ";"
    *       | attr_dcl() ";"
    *       | op_dcl() ";"
    * </PRE>
    */
   public R visit(export n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> ":"
    * scoped_name -> scoped_name()
    * nodeListOptional -> ( "," scoped_name() )*
    * </PRE>
    */
   public R visit(inheritance_spec n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.scoped_name.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeOptional -> [ "::" ]
    * identifier -> identifier()
    * nodeListOptional -> ( "::" identifier() )*
    * </PRE>
    */
   public R visit(scoped_name n, A argu) {
      R _ret=null;
      n.nodeOptional.accept(this, argu);
      n.identifier.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "const"
    * const_type -> const_type()
    * identifier -> identifier()
    * nodeToken1 -> "="
    * const_exp -> const_exp()
    * </PRE>
    */
   public R visit(const_dcl n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.const_type.accept(this, argu);
      n.identifier.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.const_exp.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> integer_type()
    *       | char_type()
    *       | boolean_type()
    *       | floating_pt_type()
    *       | string_type()
    *       | scoped_name()
    * </PRE>
    */
   public R visit(const_type n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * or_expr -> or_expr()
    * </PRE>
    */
   public R visit(const_exp n, A argu) {
      R _ret=null;
      n.or_expr.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * xor_expr -> xor_expr()
    * nodeListOptional -> ( "|" xor_expr() )*
    * </PRE>
    */
   public R visit(or_expr n, A argu) {
      R _ret=null;
      n.xor_expr.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * and_expr -> and_expr()
    * nodeListOptional -> ( "^" and_expr() )*
    * </PRE>
    */
   public R visit(xor_expr n, A argu) {
      R _ret=null;
      n.and_expr.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * shift_expr -> shift_expr()
    * nodeListOptional -> ( "&" shift_expr() )*
    * </PRE>
    */
   public R visit(and_expr n, A argu) {
      R _ret=null;
      n.shift_expr.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * add_expr -> add_expr()
    * nodeListOptional -> ( ( "&gt;&gt;" | "&lt;&lt;" ) add_expr() )*
    * </PRE>
    */
   public R visit(shift_expr n, A argu) {
      R _ret=null;
      n.add_expr.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * mult_expr -> mult_expr()
    * nodeListOptional -> ( ( "+" | "-" ) mult_expr() )*
    * </PRE>
    */
   public R visit(add_expr n, A argu) {
      R _ret=null;
      n.mult_expr.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * unary_expr -> unary_expr()
    * nodeListOptional -> ( ( "*" | "/" | "%" ) unary_expr() )*
    * </PRE>
    */
   public R visit(mult_expr n, A argu) {
      R _ret=null;
      n.unary_expr.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeOptional -> [ unary_operator() ]
    * primary_expr -> primary_expr()
    * </PRE>
    */
   public R visit(unary_expr n, A argu) {
      R _ret=null;
      n.nodeOptional.accept(this, argu);
      n.primary_expr.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> "-"
    *       | "+"
    *       | "~"
    * </PRE>
    */
   public R visit(unary_operator n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> scoped_name()
    *       | literal()
    *       | "(" const_exp() ")"
    * </PRE>
    */
   public R visit(primary_expr n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> integer_literal()
    *       | string_literal()
    *       | character_literal()
    *       | floating_pt_literal()
    *       | boolean_literal()
    * </PRE>
    */
   public R visit(literal n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> "TRUE"
    *       | "FALSE"
    * </PRE>
    */
   public R visit(boolean_literal n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * const_exp -> const_exp()
    * </PRE>
    */
   public R visit(positive_int_const n, A argu) {
      R _ret=null;
      n.const_exp.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> "typedef" type_declarator()
    *       | struct_type()
    *       | union_type()
    *       | enum_type()
    * </PRE>
    */
   public R visit(type_dcl n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * type_spec -> type_spec()
    * declarators -> declarators()
    * </PRE>
    */
   public R visit(type_declarator n, A argu) {
      R _ret=null;
      n.type_spec.accept(this, argu);
      n.declarators.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> simple_type_spec()
    *       | constr_type_spec()
    * </PRE>
    */
   public R visit(type_spec n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> base_type_spec()
    *       | template_type_spec()
    *       | scoped_name()
    * </PRE>
    */
   public R visit(simple_type_spec n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> floating_pt_type()
    *       | integer_type()
    *       | char_type()
    *       | boolean_type()
    *       | octet_type()
    *       | any_type()
    * </PRE>
    */
   public R visit(base_type_spec n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> sequence_type()
    *       | string_type()
    * </PRE>
    */
   public R visit(template_type_spec n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> struct_type()
    *       | union_type()
    *       | enum_type()
    * </PRE>
    */
   public R visit(constr_type_spec n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * declarator -> declarator()
    * nodeListOptional -> ( "," declarator() )*
    * </PRE>
    */
   public R visit(declarators n, A argu) {
      R _ret=null;
      n.declarator.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> complex_declarator()
    *       | simple_declarator()
    * </PRE>
    */
   public R visit(declarator n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * identifier -> identifier()
    * </PRE>
    */
   public R visit(simple_declarator n, A argu) {
      R _ret=null;
      n.identifier.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * array_declarator -> array_declarator()
    * </PRE>
    */
   public R visit(complex_declarator n, A argu) {
      R _ret=null;
      n.array_declarator.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> "float"
    *       | "double"
    * </PRE>
    */
   public R visit(floating_pt_type n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> signed_int()
    *       | unsigned_int()
    * </PRE>
    */
   public R visit(integer_type n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> signed_long_long_int()
    *       | signed_long_double_int()
    *       | signed_long_int()
    *       | signed_short_int()
    * </PRE>
    */
   public R visit(signed_int n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "long"
    * </PRE>
    */
   public R visit(signed_long_int n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "short"
    * </PRE>
    */
   public R visit(signed_short_int n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "long"
    * nodeToken1 -> "long"
    * </PRE>
    */
   public R visit(signed_long_long_int n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "long"
    * nodeToken1 -> "double"
    * </PRE>
    */
   public R visit(signed_long_double_int n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> unsigned_long_long_int()
    *       | unsigned_long_int()
    *       | unsigned_short_int()
    * </PRE>
    */
   public R visit(unsigned_int n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "unsigned"
    * nodeToken1 -> "long"
    * </PRE>
    */
   public R visit(unsigned_long_int n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "unsigned"
    * nodeToken1 -> "short"
    * </PRE>
    */
   public R visit(unsigned_short_int n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "unsigned"
    * nodeToken1 -> "long"
    * nodeToken2 -> "long"
    * </PRE>
    */
   public R visit(unsigned_long_long_int n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.nodeToken2.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "char"
    * </PRE>
    */
   public R visit(char_type n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "boolean"
    * </PRE>
    */
   public R visit(boolean_type n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "octet"
    * </PRE>
    */
   public R visit(octet_type n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "any"
    * </PRE>
    */
   public R visit(any_type n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "struct"
    * identifier -> identifier()
    * nodeToken1 -> "{"
    * member_list -> member_list()
    * nodeToken2 -> "}"
    * </PRE>
    */
   public R visit(struct_type n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.identifier.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.member_list.accept(this, argu);
      n.nodeToken2.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeList -> ( member() )+
    * </PRE>
    */
   public R visit(member_list n, A argu) {
      R _ret=null;
      n.nodeList.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * type_spec -> type_spec()
    * declarators -> declarators()
    * nodeToken -> ";"
    * </PRE>
    */
   public R visit(member n, A argu) {
      R _ret=null;
      n.type_spec.accept(this, argu);
      n.declarators.accept(this, argu);
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "union"
    * identifier -> identifier()
    * nodeToken1 -> "switch"
    * nodeToken2 -> "("
    * switch_type_spec -> switch_type_spec()
    * nodeToken3 -> ")"
    * nodeToken4 -> "{"
    * switch_body -> switch_body()
    * nodeToken5 -> "}"
    * </PRE>
    */
   public R visit(union_type n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.identifier.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.nodeToken2.accept(this, argu);
      n.switch_type_spec.accept(this, argu);
      n.nodeToken3.accept(this, argu);
      n.nodeToken4.accept(this, argu);
      n.switch_body.accept(this, argu);
      n.nodeToken5.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> integer_type()
    *       | char_type()
    *       | boolean_type()
    *       | enum_type()
    *       | scoped_name()
    * </PRE>
    */
   public R visit(switch_type_spec n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeList -> ( casex() )+
    * </PRE>
    */
   public R visit(switch_body n, A argu) {
      R _ret=null;
      n.nodeList.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeList -> ( case_label() )+
    * element_spec -> element_spec()
    * nodeToken -> ";"
    * </PRE>
    */
   public R visit(casex n, A argu) {
      R _ret=null;
      n.nodeList.accept(this, argu);
      n.element_spec.accept(this, argu);
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> "case" const_exp() ":"
    *       | "default" ":"
    * </PRE>
    */
   public R visit(case_label n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * type_spec -> type_spec()
    * declarator -> declarator()
    * </PRE>
    */
   public R visit(element_spec n, A argu) {
      R _ret=null;
      n.type_spec.accept(this, argu);
      n.declarator.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "enum"
    * identifier -> identifier()
    * nodeToken1 -> "{"
    * enumerator -> enumerator()
    * nodeListOptional -> ( "," enumerator() )*
    * nodeToken2 -> "}"
    * </PRE>
    */
   public R visit(enum_type n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.identifier.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.enumerator.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      n.nodeToken2.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * identifier -> identifier()
    * </PRE>
    */
   public R visit(enumerator n, A argu) {
      R _ret=null;
      n.identifier.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "sequence"
    * nodeToken1 -> "&lt;"
    * simple_type_spec -> simple_type_spec()
    * nodeOptional -> [ "," positive_int_const() ]
    * nodeToken2 -> "&gt;"
    * </PRE>
    */
   public R visit(sequence_type n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.simple_type_spec.accept(this, argu);
      n.nodeOptional.accept(this, argu);
      n.nodeToken2.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "string"
    * nodeOptional -> [ "&lt;" positive_int_const() "&gt;" ]
    * </PRE>
    */
   public R visit(string_type n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.nodeOptional.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * identifier -> identifier()
    * nodeList -> ( fixed_array_size() )+
    * </PRE>
    */
   public R visit(array_declarator n, A argu) {
      R _ret=null;
      n.identifier.accept(this, argu);
      n.nodeList.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "["
    * positive_int_const -> positive_int_const()
    * nodeToken1 -> "]"
    * </PRE>
    */
   public R visit(fixed_array_size n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.positive_int_const.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeOptional -> [ "readonly" ]
    * nodeToken -> "attribute"
    * param_type_spec -> param_type_spec()
    * simple_declarator -> simple_declarator()
    * nodeListOptional -> ( "," simple_declarator() )*
    * </PRE>
    */
   public R visit(attr_dcl n, A argu) {
      R _ret=null;
      n.nodeOptional.accept(this, argu);
      n.nodeToken.accept(this, argu);
      n.param_type_spec.accept(this, argu);
      n.simple_declarator.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "exception"
    * identifier -> identifier()
    * nodeToken1 -> "{"
    * nodeListOptional -> ( member() )*
    * nodeToken2 -> "}"
    * </PRE>
    */
   public R visit(except_dcl n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.identifier.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      n.nodeToken2.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeOptional -> [ op_attribute() ]
    * op_type_spec -> op_type_spec()
    * identifier -> identifier()
    * parameter_dcls -> parameter_dcls()
    * nodeOptional1 -> [ raises_expr() ]
    * nodeOptional2 -> [ context_expr() ]
    * </PRE>
    */
   public R visit(op_dcl n, A argu) {
      R _ret=null;
      n.nodeOptional.accept(this, argu);
      n.op_type_spec.accept(this, argu);
      n.identifier.accept(this, argu);
      n.parameter_dcls.accept(this, argu);
      n.nodeOptional1.accept(this, argu);
      n.nodeOptional2.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "oneway"
    * </PRE>
    */
   public R visit(op_attribute n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> param_type_spec()
    *       | "void"
    * </PRE>
    */
   public R visit(op_type_spec n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "("
    * nodeOptional -> [ param_dcl() ( "," param_dcl() )* ]
    * nodeToken1 -> ")"
    * </PRE>
    */
   public R visit(parameter_dcls n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.nodeOptional.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * param_attribute -> param_attribute()
    * param_type_spec -> param_type_spec()
    * simple_declarator -> simple_declarator()
    * </PRE>
    */
   public R visit(param_dcl n, A argu) {
      R _ret=null;
      n.param_attribute.accept(this, argu);
      n.param_type_spec.accept(this, argu);
      n.simple_declarator.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> "in"
    *       | "out"
    *       | "inout"
    * </PRE>
    */
   public R visit(param_attribute n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "raises"
    * nodeToken1 -> "("
    * scoped_name -> scoped_name()
    * nodeListOptional -> ( "," scoped_name() )*
    * nodeToken2 -> ")"
    * </PRE>
    */
   public R visit(raises_expr n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.scoped_name.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      n.nodeToken2.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> "context"
    * nodeToken1 -> "("
    * string_literal -> string_literal()
    * nodeListOptional -> ( "," string_literal() )*
    * nodeToken2 -> ")"
    * </PRE>
    */
   public R visit(context_expr n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      n.nodeToken1.accept(this, argu);
      n.string_literal.accept(this, argu);
      n.nodeListOptional.accept(this, argu);
      n.nodeToken2.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> base_type_spec()
    *       | string_type()
    *       | scoped_name()
    * </PRE>
    */
   public R visit(param_type_spec n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> &lt;ID&gt;
    * </PRE>
    */
   public R visit(identifier n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> &lt;OCTALINT&gt;
    *       | &lt;DECIMALINT&gt;
    *       | &lt;HEXADECIMALINT&gt;
    * </PRE>
    */
   public R visit(integer_literal n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> &lt;STRING&gt;
    * </PRE>
    */
   public R visit(string_literal n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeToken -> &lt;CHARACTER&gt;
    * </PRE>
    */
   public R visit(character_literal n, A argu) {
      R _ret=null;
      n.nodeToken.accept(this, argu);
      return _ret;
   }

   /**
    * <PRE>
    * nodeChoice -> &lt;FLOATONE&gt;
    *       | &lt;FLOATTWO&gt;
    * </PRE>
    */
   public R visit(floating_pt_literal n, A argu) {
      R _ret=null;
      n.nodeChoice.accept(this, argu);
      return _ret;
   }

}
