//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.24 at 07:25:27 Œß‘O GMT 
//


package org.openrtp.namespaces.rtc;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for actions complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="actions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OnInitialize" type="{http://www.openrtp.org/namespaces/rtc}action_status"/>
 *         &lt;element name="OnFinalize" type="{http://www.openrtp.org/namespaces/rtc}action_status"/>
 *         &lt;element name="OnStartup" type="{http://www.openrtp.org/namespaces/rtc}action_status"/>
 *         &lt;element name="OnShutdown" type="{http://www.openrtp.org/namespaces/rtc}action_status"/>
 *         &lt;element name="OnActivated" type="{http://www.openrtp.org/namespaces/rtc}action_status"/>
 *         &lt;element name="OnDeactivated" type="{http://www.openrtp.org/namespaces/rtc}action_status"/>
 *         &lt;element name="OnAborting" type="{http://www.openrtp.org/namespaces/rtc}action_status"/>
 *         &lt;element name="OnError" type="{http://www.openrtp.org/namespaces/rtc}action_status"/>
 *         &lt;element name="OnReset" type="{http://www.openrtp.org/namespaces/rtc}action_status"/>
 *         &lt;element name="OnExecute" type="{http://www.openrtp.org/namespaces/rtc}action_status"/>
 *         &lt;element name="OnStateUpdate" type="{http://www.openrtp.org/namespaces/rtc}action_status"/>
 *         &lt;element name="OnRateChanged" type="{http://www.openrtp.org/namespaces/rtc}action_status"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "actions", propOrder = {
    "onInitialize",
    "onFinalize",
    "onStartup",
    "onShutdown",
    "onActivated",
    "onDeactivated",
    "onAborting",
    "onError",
    "onReset",
    "onExecute",
    "onStateUpdate",
    "onRateChanged"
})
public class Actions {

    @XmlElement(name = "OnInitialize", required = true)
    protected ActionStatus onInitialize;
    @XmlElement(name = "OnFinalize", required = true)
    protected ActionStatus onFinalize;
    @XmlElement(name = "OnStartup", required = true)
    protected ActionStatus onStartup;
    @XmlElement(name = "OnShutdown", required = true)
    protected ActionStatus onShutdown;
    @XmlElement(name = "OnActivated", required = true)
    protected ActionStatus onActivated;
    @XmlElement(name = "OnDeactivated", required = true)
    protected ActionStatus onDeactivated;
    @XmlElement(name = "OnAborting", required = true)
    protected ActionStatus onAborting;
    @XmlElement(name = "OnError", required = true)
    protected ActionStatus onError;
    @XmlElement(name = "OnReset", required = true)
    protected ActionStatus onReset;
    @XmlElement(name = "OnExecute", required = true)
    protected ActionStatus onExecute;
    @XmlElement(name = "OnStateUpdate", required = true)
    protected ActionStatus onStateUpdate;
    @XmlElement(name = "OnRateChanged", required = true)
    protected ActionStatus onRateChanged;

    /**
     * Gets the value of the onInitialize property.
     * 
     * @return
     *     possible object is
     *     {@link ActionStatus }
     *     
     */
    public ActionStatus getOnInitialize() {
        return onInitialize;
    }

    /**
     * Sets the value of the onInitialize property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionStatus }
     *     
     */
    public void setOnInitialize(ActionStatus value) {
        this.onInitialize = value;
    }

    /**
     * Gets the value of the onFinalize property.
     * 
     * @return
     *     possible object is
     *     {@link ActionStatus }
     *     
     */
    public ActionStatus getOnFinalize() {
        return onFinalize;
    }

    /**
     * Sets the value of the onFinalize property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionStatus }
     *     
     */
    public void setOnFinalize(ActionStatus value) {
        this.onFinalize = value;
    }

    /**
     * Gets the value of the onStartup property.
     * 
     * @return
     *     possible object is
     *     {@link ActionStatus }
     *     
     */
    public ActionStatus getOnStartup() {
        return onStartup;
    }

    /**
     * Sets the value of the onStartup property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionStatus }
     *     
     */
    public void setOnStartup(ActionStatus value) {
        this.onStartup = value;
    }

    /**
     * Gets the value of the onShutdown property.
     * 
     * @return
     *     possible object is
     *     {@link ActionStatus }
     *     
     */
    public ActionStatus getOnShutdown() {
        return onShutdown;
    }

    /**
     * Sets the value of the onShutdown property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionStatus }
     *     
     */
    public void setOnShutdown(ActionStatus value) {
        this.onShutdown = value;
    }

    /**
     * Gets the value of the onActivated property.
     * 
     * @return
     *     possible object is
     *     {@link ActionStatus }
     *     
     */
    public ActionStatus getOnActivated() {
        return onActivated;
    }

    /**
     * Sets the value of the onActivated property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionStatus }
     *     
     */
    public void setOnActivated(ActionStatus value) {
        this.onActivated = value;
    }

    /**
     * Gets the value of the onDeactivated property.
     * 
     * @return
     *     possible object is
     *     {@link ActionStatus }
     *     
     */
    public ActionStatus getOnDeactivated() {
        return onDeactivated;
    }

    /**
     * Sets the value of the onDeactivated property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionStatus }
     *     
     */
    public void setOnDeactivated(ActionStatus value) {
        this.onDeactivated = value;
    }

    /**
     * Gets the value of the onAborting property.
     * 
     * @return
     *     possible object is
     *     {@link ActionStatus }
     *     
     */
    public ActionStatus getOnAborting() {
        return onAborting;
    }

    /**
     * Sets the value of the onAborting property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionStatus }
     *     
     */
    public void setOnAborting(ActionStatus value) {
        this.onAborting = value;
    }

    /**
     * Gets the value of the onError property.
     * 
     * @return
     *     possible object is
     *     {@link ActionStatus }
     *     
     */
    public ActionStatus getOnError() {
        return onError;
    }

    /**
     * Sets the value of the onError property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionStatus }
     *     
     */
    public void setOnError(ActionStatus value) {
        this.onError = value;
    }

    /**
     * Gets the value of the onReset property.
     * 
     * @return
     *     possible object is
     *     {@link ActionStatus }
     *     
     */
    public ActionStatus getOnReset() {
        return onReset;
    }

    /**
     * Sets the value of the onReset property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionStatus }
     *     
     */
    public void setOnReset(ActionStatus value) {
        this.onReset = value;
    }

    /**
     * Gets the value of the onExecute property.
     * 
     * @return
     *     possible object is
     *     {@link ActionStatus }
     *     
     */
    public ActionStatus getOnExecute() {
        return onExecute;
    }

    /**
     * Sets the value of the onExecute property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionStatus }
     *     
     */
    public void setOnExecute(ActionStatus value) {
        this.onExecute = value;
    }

    /**
     * Gets the value of the onStateUpdate property.
     * 
     * @return
     *     possible object is
     *     {@link ActionStatus }
     *     
     */
    public ActionStatus getOnStateUpdate() {
        return onStateUpdate;
    }

    /**
     * Sets the value of the onStateUpdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionStatus }
     *     
     */
    public void setOnStateUpdate(ActionStatus value) {
        this.onStateUpdate = value;
    }

    /**
     * Gets the value of the onRateChanged property.
     * 
     * @return
     *     possible object is
     *     {@link ActionStatus }
     *     
     */
    public ActionStatus getOnRateChanged() {
        return onRateChanged;
    }

    /**
     * Sets the value of the onRateChanged property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionStatus }
     *     
     */
    public void setOnRateChanged(ActionStatus value) {
        this.onRateChanged = value;
    }

}
