//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.04.24 at 07:25:27 Œß‘O GMT 
//


package org.openrtp.namespaces.rtc;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.openrtp.namespaces.rtc package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RtcProfile_QNAME = new QName("http://www.openrtp.org/namespaces/rtc", "RtcProfile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openrtp.namespaces.rtc
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ConfigurationSet }
     * 
     */
    public ConfigurationSet createConfigurationSet() {
        return new ConfigurationSet();
    }

    /**
     * Create an instance of {@link Configuration }
     * 
     */
    public Configuration createConfiguration() {
        return new Configuration();
    }

    /**
     * Create an instance of {@link DocDataport }
     * 
     */
    public DocDataport createDocDataport() {
        return new DocDataport();
    }

    /**
     * Create an instance of {@link BasicInfoDoc }
     * 
     */
    public BasicInfoDoc createBasicInfoDoc() {
        return new BasicInfoDoc();
    }

    /**
     * Create an instance of {@link DocAction }
     * 
     */
    public DocAction createDocAction() {
        return new DocAction();
    }

    /**
     * Create an instance of {@link Cxxlang }
     * 
     */
    public Cxxlang createCxxlang() {
        return new Cxxlang();
    }

    /**
     * Create an instance of {@link Actions }
     * 
     */
    public Actions createActions() {
        return new Actions();
    }

    /**
     * Create an instance of {@link Javalang }
     * 
     */
    public Javalang createJavalang() {
        return new Javalang();
    }

    /**
     * Create an instance of {@link DocBasic }
     * 
     */
    public DocBasic createDocBasic() {
        return new DocBasic();
    }

    /**
     * Create an instance of {@link BasicInfoExt }
     * 
     */
    public BasicInfoExt createBasicInfoExt() {
        return new BasicInfoExt();
    }

    /**
     * Create an instance of {@link DocServiceinterface }
     * 
     */
    public DocServiceinterface createDocServiceinterface() {
        return new DocServiceinterface();
    }

    /**
     * Create an instance of {@link BasicInfo }
     * 
     */
    public BasicInfo createBasicInfo() {
        return new BasicInfo();
    }

    /**
     * Create an instance of {@link Serviceinterface }
     * 
     */
    public Serviceinterface createServiceinterface() {
        return new Serviceinterface();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link DocConfiguration }
     * 
     */
    public DocConfiguration createDocConfiguration() {
        return new DocConfiguration();
    }

    /**
     * Create an instance of {@link Language }
     * 
     */
    public Language createLanguage() {
        return new Language();
    }

    /**
     * Create an instance of {@link ActionStatus }
     * 
     */
    public ActionStatus createActionStatus() {
        return new ActionStatus();
    }

    /**
     * Create an instance of {@link ServiceportDoc }
     * 
     */
    public ServiceportDoc createServiceportDoc() {
        return new ServiceportDoc();
    }

    /**
     * Create an instance of {@link DocServiceport }
     * 
     */
    public DocServiceport createDocServiceport() {
        return new DocServiceport();
    }

    /**
     * Create an instance of {@link DataportExt }
     * 
     */
    public DataportExt createDataportExt() {
        return new DataportExt();
    }

    /**
     * Create an instance of {@link ConfigurationDoc }
     * 
     */
    public ConfigurationDoc createConfigurationDoc() {
        return new ConfigurationDoc();
    }

    /**
     * Create an instance of {@link ServiceinterfaceDoc }
     * 
     */
    public ServiceinterfaceDoc createServiceinterfaceDoc() {
        return new ServiceinterfaceDoc();
    }

    /**
     * Create an instance of {@link Dataport }
     * 
     */
    public Dataport createDataport() {
        return new Dataport();
    }

    /**
     * Create an instance of {@link ActionStatusDoc }
     * 
     */
    public ActionStatusDoc createActionStatusDoc() {
        return new ActionStatusDoc();
    }

    /**
     * Create an instance of {@link RtcProfile }
     * 
     */
    public RtcProfile createRtcProfile() {
        return new RtcProfile();
    }

    /**
     * Create an instance of {@link Serviceport }
     * 
     */
    public Serviceport createServiceport() {
        return new Serviceport();
    }

    /**
     * Create an instance of {@link DataportDoc }
     * 
     */
    public DataportDoc createDataportDoc() {
        return new DataportDoc();
    }

    /**
     * Create an instance of {@link ServiceportExt }
     * 
     */
    public ServiceportExt createServiceportExt() {
        return new ServiceportExt();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RtcProfile }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.openrtp.org/namespaces/rtc", name = "RtcProfile")
    public JAXBElement<RtcProfile> createRtcProfile(RtcProfile value) {
        return new JAXBElement<RtcProfile>(_RtcProfile_QNAME, RtcProfile.class, null, value);
    }

}
